### ISSUE TITLE
拉取文件自定义请求头

### ISSUE THREAD

**Issue by SaboZhang** [EmptyDreams/swpp-backends#1]
能否增加一项关于请求头Referer 的配置呢，之前因为在CDN设置了Referer 防盗链，然后hexo swpp 一直 403。 经过确认测试确认是因为设置了Referer 。不过不是很重要，一般需要让别人可以连自己的网站都不会设置Referer 防盗链，但考虑到某些特定场景和需求，增加这一配置选项可能会更加灵活和方便。这只是一个不成熟的小小建议，大佬如果能增加最好。

**Comment by EmptyDreams** [comment]
预计在 swpp v3 提供，近期比较忙可能会拖的比较久

**Comment by EmptyDreams** [comment]
V3 已经支持自定义请求头，但是功能还没写完
