### ISSUE TITLE
现代化配置文件命名与加载

### ISSUE THREAD

**Issue by KazariEX** [EmptyDreams/swpp-backends#2]
当前配置文件的加载方式为 CJS Require，并且需要按照 CJS 的格式书写，建议统一使用纯 ESM 的方式加载，并按照形如 `swpp.config.ts` 的格式为配置文件命名（可以使用 [unjs/c12](https://github.com/unjs/c12), [so1ve/yajuu](https://github.com/so1ve/yajuu) 等）。

此时可以像其他工具一样导出一个辅助函数 `defineConfig`，为用户提供完备的类型提示。

**Comment by EmptyDreams** [comment]
已经支持使用 js ts cjs cts mjs mts 文件编写配置、自定义配置文件名
